# Generated by Django 6.0.2 on 2026-04-19 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('workout_completed', 'Workout Completed'), ('meal_logged', 'Meal Logged'), ('goal_updated', 'Goal Updated'), ('weight_updated', 'Weight Updated'), ('profile_updated', 'Profile Updated')], max_length=50)),
                ('activity_data', models.JSONField(blank=True, help_text='Additional data about the activity', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('target_weight', models.FloatField(blank=True, help_text='Target weight in kg', null=True)),
                ('fitness_goal', models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('maintain', 'Maintain Weight'), ('eat_healthier', 'Eat Healthier')], max_length=50, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Light (1-3 days/week)'), ('moderate', 'Moderate (3-5 days/week)'), ('active', 'Active (6-7 days/week)'), ('very_active', 'Very Active (twice per day)')], max_length=50, null=True)),
                ('workout_duration', models.IntegerField(blank=True, help_text='Preferred workout duration in minutes', null=True)),
                ('workout_types', models.JSONField(blank=True, help_text='List of preferred workout types', null=True)),
                ('dietary_preferences', models.JSONField(blank=True, help_text='List of dietary preferences', null=True)),
                ('allergies', models.JSONField(blank=True, help_text='List of food allergies', null=True)),
                ('medical_conditions', models.JSONField(blank=True, help_text='List of medical conditions', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
