# Generated by Django 6.0.3 on 2026-03-20 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Day number in the workout program')),
                ('exercises', models.JSONField(help_text='List of exercises with sets, reps, and rest periods')),
                ('workout_type', models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('flexibility', 'Flexibility'), ('mixed', 'Mixed Workout')], default='mixed', max_length=50)),
                ('estimated_duration', models.IntegerField(help_text='Estimated workout duration in minutes')),
                ('equipment_needed', models.JSONField(default=list, help_text='List of equipment needed for this workout')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('intensity_score', models.FloatField(default=5.0, help_text='Workout intensity score (1-10)')),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('adaptation_score', models.FloatField(default=0.0, help_text="How well this workout adapts to user's progress")),
                ('completed', models.BooleanField(default=False)),
                ('completion_time', models.DurationField(blank=True, help_text='Actual time taken to complete workout', null=True)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='User workout rating 1-5', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout Plan',
                'verbose_name_plural': 'Workout Plans',
                'db_table': 'workout_plans',
                'ordering': ['day'],
                'unique_together': {('user', 'day')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text="User's preferred workout difficulty level", max_length=20)),
                ('workout_type_preference', models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('flexibility', 'Flexibility'), ('mixed', 'Mixed Workout')], default='mixed', help_text="User's preferred type of workout", max_length=50)),
                ('preferred_session_duration', models.IntegerField(default=30, help_text='Preferred workout duration in minutes')),
                ('preferred_workout_days_per_week', models.IntegerField(default=3, help_text='Number of workout days preferred per week')),
                ('equipment_available', models.JSONField(default=list, help_text='List of equipment available to the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout Preferences',
                'verbose_name_plural': 'Workout Preferences',
                'db_table': 'workout_preferences',
            },
        ),
        migrations.CreateModel(
            name='WorkoutProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_workouts', models.IntegerField(default=0)),
                ('workout_streak', models.IntegerField(default=0)),
                ('total_workout_time', models.DurationField(default='00:00:00', help_text='Total time spent working out')),
                ('total_calories_burned', models.IntegerField(default=0)),
                ('max_bench_press', models.FloatField(blank=True, help_text='Maximum bench press weight in kg', null=True)),
                ('max_squat', models.FloatField(blank=True, help_text='Maximum squat weight in kg', null=True)),
                ('max_deadlift', models.FloatField(blank=True, help_text='Maximum deadlift weight in kg', null=True)),
                ('max_run_distance', models.FloatField(blank=True, help_text='Maximum running distance in km', null=True)),
                ('best_5k_time', models.DurationField(blank=True, help_text='Best 5K run time', null=True)),
                ('performance_score', models.FloatField(default=0.0, help_text='AI-calculated performance score (0-100)')),
                ('achievement_badges', models.JSONField(default=list, help_text='List of workout-related achievement badges')),
                ('ai_insights', models.TextField(blank=True, help_text='AI-generated workout insights and recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout Progress',
                'verbose_name_plural': 'Workout Progress',
                'db_table': 'workout_progress',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Actual workout duration', null=True)),
                ('exercises_completed', models.JSONField(default=list, help_text='List of exercises actually completed')),
                ('workout_type', models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('flexibility', 'Flexibility'), ('mixed', 'Mixed Workout')], default='mixed', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('calories_burned', models.IntegerField(default=0, help_text='Estimated calories burned')),
                ('difficulty_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='User perceived difficulty 1-5', null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about the workout session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(blank=True, help_text='Associated workout plan if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workout.workoutplan')),
            ],
            options={
                'verbose_name': 'Workout Session',
                'verbose_name_plural': 'Workout Sessions',
                'db_table': 'workout_sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
