# Generated by Django 6.0.2 on 2026-03-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutPreferences',
        ),
    ]
