# Generated by Django 6.0.1 on 2026-03-03 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='achievement',
            new_name='frontend_ac_user_id_1ca834_idx',
            old_name='frontend_achi_user_id__2b6e9a_idx',
        ),
        migrations.RenameIndex(
            model_name='achievement',
            new_name='frontend_ac_achieve_6c5b49_idx',
            old_name='frontend_achi_achievem_8c3f5d_idx',
        ),
        migrations.RenameIndex(
            model_name='exerciselog',
            new_name='frontend_ex_workout_e1bc4a_idx',
            old_name='frontend_exer_workout_s_7c3d5e_idx',
        ),
        migrations.RenameIndex(
            model_name='exerciselog',
            new_name='frontend_ex_created_128fc8_idx',
            old_name='frontend_exer__created_5f8b9a_idx',
        ),
        migrations.RenameIndex(
            model_name='meallog',
            new_name='frontend_me_user_id_961f72_idx',
            old_name='frontend_meal_user_id__4e8c7f_idx',
        ),
        migrations.RenameIndex(
            model_name='meallog',
            new_name='frontend_me_user_id_aa47b1_idx',
            old_name='frontend_meal_user_id_7a3d2b_idx',
        ),
        migrations.RenameIndex(
            model_name='meallog',
            new_name='frontend_me_created_abc3f5_idx',
            old_name='frontend_meal__created_9f5e8c_idx',
        ),
        migrations.RenameIndex(
            model_name='progresssnapshot',
            new_name='frontend_pr_user_id_186c9c_idx',
            old_name='frontend_prog_user_id__a2c4d6_idx',
        ),
        migrations.RenameIndex(
            model_name='progresssnapshot',
            new_name='frontend_pr_created_338914_idx',
            old_name='frontend_prog__created_3e7f8b_idx',
        ),
        migrations.RenameIndex(
            model_name='streak',
            new_name='frontend_st_user_id_5b4d9c_idx',
            old_name='frontend_stre_user_id__9c2d5e_idx',
        ),
        migrations.RenameIndex(
            model_name='streak',
            new_name='frontend_st_user_id_a6c1fb_idx',
            old_name='frontend_stre_user_id_6f8a3b_idx',
        ),
        migrations.RenameIndex(
            model_name='streak',
            new_name='frontend_st_updated_35f96d_idx',
            old_name='frontend_stre__updated_2c7e9a_idx',
        ),
        migrations.RenameIndex(
            model_name='workoutsession',
            new_name='frontend_wo_user_id_991f8f_idx',
            old_name='frontend_work_user_id_8f4a9a_idx',
        ),
        migrations.RenameIndex(
            model_name='workoutsession',
            new_name='frontend_wo_user_id_4e0059_idx',
            old_name='frontend_work_user_id_4b5f3b_idx',
        ),
        migrations.RenameIndex(
            model_name='workoutsession',
            new_name='frontend_wo_created_51c055_idx',
            old_name='frontend_work__created_1e4a2c_idx',
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='form_rating',
            field=models.IntegerField(blank=True, help_text="User's rating of exercise form (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='difficulty_rating',
            field=models.IntegerField(blank=True, help_text="User's rating of workout difficulty (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
