# Generated by Django 6.0.3 on 2026-03-20 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_frontend_achi_user_id__2b6e9a_idx_frontend_ac_user_id_1ca834_idx_and_more'),
        ('workout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontend_workout_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='workout_plan',
            field=models.ForeignKey(blank=True, help_text='The AI-generated workout plan this session follows', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_sessions', to='workout.WorkoutPlan'),
        ),
    ]
