# Generated by Django 6.0.2 on 2026-04-21 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('keto', 'Ketogenic'), ('paleo', 'Paleo'), ('mediterranean', 'Mediterranean'), ('low_carb', 'Low Carb'), ('low_fat', 'Low Fat'), ('gluten_free', 'Gluten-Free')], default='omnivore', help_text='Primary diet type preference', max_length=50)),
                ('restrictions', models.JSONField(default=list, help_text='List of dietary restrictions (e.g., lactose-free, nut-free)')),
                ('allergies', models.JSONField(default=list, help_text='List of food allergies')),
                ('disliked_foods', models.JSONField(default=list, help_text='List of foods user dislikes')),
                ('preferred_foods', models.JSONField(default=list, help_text='List of foods user prefers')),
                ('meals_per_day', models.IntegerField(default=3, help_text='Number of meals preferred per day')),
                ('snack_frequency', models.CharField(choices=[('never', 'Never'), ('rarely', 'Rarely'), ('sometimes', 'Sometimes'), ('daily', 'Daily'), ('multiple', 'Multiple times per day')], default='sometimes', help_text='How often user prefers snacks', max_length=20)),
                ('target_calories', models.IntegerField(blank=True, help_text='Target daily calories (calculated automatically if not set)', null=True)),
                ('macro_split', models.JSONField(default=dict, help_text='Preferred macronutrient split as percentages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dietary Preferences',
                'verbose_name_plural': 'Dietary Preferences',
                'db_table': 'nutrition_dietary_preferences',
            },
        ),
        migrations.CreateModel(
            name='FoodDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Food name', max_length=200)),
                ('category', models.CharField(help_text='Food category (e.g., fruits, vegetables, proteins)', max_length=100)),
                ('calories_per_100g', models.IntegerField(help_text='Calories per 100g serving')),
                ('protein_per_100g', models.FloatField(default=0, help_text='Protein in grams per 100g')),
                ('carbs_per_100g', models.FloatField(default=0, help_text='Carbohydrates in grams per 100g')),
                ('fat_per_100g', models.FloatField(default=0, help_text='Fat in grams per 100g')),
                ('fiber_per_100g', models.FloatField(default=0, help_text='Fiber in grams per 100g')),
                ('sugar_per_100g', models.FloatField(default=0, help_text='Sugar in grams per 100g')),
                ('sodium_per_100g', models.FloatField(default=0, help_text='Sodium in mg per 100g')),
                ('is_organic', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('allergens', models.JSONField(default=list, help_text='List of potential allergens')),
                ('suitable_for', models.JSONField(default=list, help_text='List of diet types this food is suitable for')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food Database',
                'verbose_name_plural': 'Food Database',
                'db_table': 'nutrition_food_database',
                'ordering': ['name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='NutritionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('meal_plan_adherence', models.FloatField(default=0.0, help_text='Percentage of meals followed as planned (0-100)')),
                ('calorie_consistency', models.FloatField(default=0.0, help_text='How consistent calorie intake is with targets (0-100)')),
                ('macro_balance_score', models.FloatField(default=0.0, help_text='How well macronutrients are balanced (0-100)')),
                ('blood_pressure_systolic', models.IntegerField(blank=True, help_text='Systolic blood pressure', null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, help_text='Diastolic blood pressure', null=True)),
                ('resting_heart_rate', models.IntegerField(blank=True, help_text='Resting heart rate in bpm', null=True)),
                ('nutrition_score', models.FloatField(default=0.0, help_text='AI-calculated nutrition score (0-100)')),
                ('achievement_badges', models.JSONField(default=list, help_text='List of nutrition-related achievement badges')),
                ('ai_insights', models.TextField(blank=True, help_text='AI-generated nutrition insights and recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition Progress',
                'verbose_name_plural': 'Nutrition Progress',
                'db_table': 'nutrition_progress',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meals', models.JSONField(help_text='Meal data including breakfast, lunch, dinner, snacks')),
                ('total_calories', models.IntegerField()),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('sodium', models.FloatField(default=0)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in meal plan quality (0-1)')),
                ('approach', models.CharField(choices=[('ml_based', 'ML Based'), ('rule_based', 'Rule Based'), ('hybrid', 'Hybrid')], default='ml_based', help_text='Approach used to generate meal plan', max_length=20)),
                ('adaptation_applied', models.BooleanField(default=False, help_text='Whether real-time adaptation was applied')),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='User rating 1-5', null=True)),
                ('user_feedback', models.TextField(blank=True, help_text='User feedback on meal plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'db_table': 'nutrition_meal_plans',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast', models.JSONField(default=list, help_text='Breakfast food items and quantities')),
                ('lunch', models.JSONField(default=list, help_text='Lunch food items and quantities')),
                ('dinner', models.JSONField(default=list, help_text='Dinner food items and quantities')),
                ('snacks', models.JSONField(default=list, help_text='Snack food items and quantities')),
                ('total_calories', models.IntegerField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('water_intake_ml', models.IntegerField(default=0, help_text='Daily water intake in milliliters')),
                ('notes', models.TextField(blank=True, help_text="User notes about the day's nutrition")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition Log',
                'verbose_name_plural': 'Nutrition Logs',
                'db_table': 'nutrition_logs',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
