# Generated by Django 6.0.2 on 2026-03-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichathistory',
            name='ai_provider_used',
            field=models.CharField(default='rule-based', help_text='Which AI provider was used for this response', max_length=50),
        ),
    ]
