# Generated by Django 5.1.2 on 2026-02-11 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('intent_detected', models.CharField(help_text='AI-detected intent of user message', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in response accuracy (0-1)')),
                ('helpful', models.BooleanField(blank=True, help_text='Was the response helpful?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chat History',
                'verbose_name_plural': 'AI Chat Histories',
                'db_table': 'ai_chat_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('bmi', models.FloatField(help_text='Body Mass Index')),
                ('fitness_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('endurance', 'Endurance'), ('strength', 'Strength Building')], default='maintenance', max_length=50)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary - Little or no exercise'), ('light', 'Light - Exercise 1-3 days/week'), ('moderate', 'Moderate - Exercise 3-5 days/week'), ('active', 'Active - Exercise 6-7 days/week'), ('very_active', 'Very Active - Physical job or training twice/day')], default='moderate', max_length=30)),
                ('dietary_preferences', models.JSONField(default=dict, help_text='Dietary restrictions and preferences')),
                ('medical_conditions', models.JSONField(default=list, help_text='List of medical conditions')),
                ('allergies', models.JSONField(default=list, help_text='List of food allergies')),
                ('target_weight', models.FloatField(blank=True, help_text='Target weight in kg', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Metrics',
                'verbose_name_plural': 'Health Metrics',
                'db_table': 'ai_health_metrics',
            },
        ),
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('muscle_mass', models.FloatField(blank=True, null=True)),
                ('workout_streak', models.IntegerField(default=0)),
                ('total_workouts', models.IntegerField(default=0)),
                ('calories_burned', models.IntegerField(default=0)),
                ('progress_score', models.FloatField(default=0.0, help_text='AI-calculated progress score (0-100)')),
                ('achievement_badges', models.JSONField(default=list, help_text='List of earned achievement badges')),
                ('ai_insights', models.TextField(blank=True, help_text='AI-generated insights and recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Tracking',
                'verbose_name_plural': 'Progress Tracking',
                'db_table': 'ai_progress_tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meals', models.JSONField(help_text='Meal data including breakfast, lunch, dinner, snacks')),
                ('total_calories', models.IntegerField()),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in meal plan quality (0-1)')),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='User rating 1-5', null=True)),
                ('user_feedback', models.TextField(blank=True, help_text='User feedback on meal plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'db_table': 'ai_meal_plans',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Day number in the workout program')),
                ('exercises', models.JSONField(help_text='List of exercises with sets, reps, and rest periods')),
                ('workout_type', models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('flexibility', 'Flexibility'), ('mixed', 'Mixed Workout')], default='mixed', max_length=50)),
                ('estimated_duration', models.IntegerField(help_text='Estimated workout duration in minutes')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('intensity_score', models.FloatField(default=5.0, help_text='Workout intensity score (1-10)')),
                ('equipment_needed', models.JSONField(default=list, help_text='List of equipment needed for this workout')),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('adaptation_score', models.FloatField(default=0.0, help_text="How well this workout adapts to user's progress")),
                ('completed', models.BooleanField(default=False)),
                ('completion_time', models.DurationField(blank=True, help_text='Actual time taken to complete workout', null=True)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='User workout rating 1-5', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout Plan',
                'verbose_name_plural': 'Workout Plans',
                'db_table': 'ai_workout_plans',
                'ordering': ['day'],
                'unique_together': {('user', 'day')},
            },
        ),
    ]
