# Generated by Django 5.1.2 on 2026-02-11 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('intent_detected', models.CharField(help_text='AI-detected intent of user message', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in response accuracy (0-1)')),
                ('helpful', models.BooleanField(blank=True, help_text='Was the response helpful?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Chat History',
                'verbose_name_plural': 'AI Chat Histories',
                'db_table': 'ai_chat_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('bmi', models.FloatField(help_text='Body Mass Index')),
                ('fitness_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('endurance', 'Endurance'), ('strength', 'Strength Building')], default='maintenance', max_length=50)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary - Little or no exercise'), ('light', 'Light - Exercise 1-3 days/week'), ('moderate', 'Moderate - Exercise 3-5 days/week'), ('active', 'Active - Exercise 6-7 days/week'), ('very_active', 'Very Active - Physical job or training twice/day')], default='moderate', max_length=30)),
                ('dietary_preferences', models.JSONField(default=dict, help_text='Dietary restrictions and preferences')),
                ('medical_conditions', models.JSONField(default=list, help_text='List of medical conditions')),
                ('allergies', models.JSONField(default=list, help_text='List of food allergies')),
                ('target_weight', models.FloatField(blank=True, help_text='Target weight in kg', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Metrics',
                'verbose_name_plural': 'Health Metrics',
                'db_table': 'ai_health_metrics',
            },
        ),
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('body_fat_percentage', models.FloatField(blank=True, null=True)),
                ('muscle_mass', models.FloatField(blank=True, null=True)),
                ('workout_streak', models.IntegerField(default=0)),
                ('total_workouts', models.IntegerField(default=0)),
                ('calories_burned', models.IntegerField(default=0)),
                ('nutrition_adherence', models.FloatField(default=0.0, help_text='How well user follows nutrition plans (0-100)')),
                ('progress_score', models.FloatField(default=0.0, help_text='AI-calculated overall progress score (0-100)')),
                ('achievement_badges', models.JSONField(default=list, help_text='List of earned achievement badges')),
                ('ai_insights', models.TextField(blank=True, help_text='AI-generated insights and recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Tracking',
                'verbose_name_plural': 'Progress Tracking',
                'db_table': 'ai_progress_tracking',
                'ordering': ['-created_at'],
            },
        ),
    ]
