# Generated by Django 6.0.3 on 2026-03-19 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text="User's preferred workout difficulty level", max_length=20)),
                ('workout_type_preference', models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('flexibility', 'Flexibility'), ('mixed', 'Mixed Workout')], default='mixed', help_text="User's preferred type of workout", max_length=50)),
                ('preferred_session_duration', models.IntegerField(default=30, help_text='Preferred workout duration in minutes')),
                ('preferred_workout_days_per_week', models.IntegerField(default=3, help_text='Number of workout days preferred per week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout Preferences',
                'verbose_name_plural': 'Workout Preferences',
                'db_table': 'ai_workout_preferences',
            },
        ),
    ]
