# Generated by Django 6.0.2 on 2026-04-19 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0002_aichathistory_ai_provider_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_type', models.CharField(choices=[('nutrition', 'Nutrition Recommendation'), ('workout', 'Workout Recommendation')], max_length=50)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('total_predictions', models.IntegerField(default=0)),
                ('ml_based_predictions', models.IntegerField(default=0)),
                ('rule_based_predictions', models.IntegerField(default=0)),
                ('hybrid_predictions', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('ml_success_rate', models.FloatField(default=0.0)),
                ('rule_based_success_rate', models.FloatField(default=0.0)),
                ('avg_confidence_score', models.FloatField(blank=True, null=True)),
                ('avg_ml_confidence', models.FloatField(blank=True, null=True)),
                ('avg_user_rating', models.FloatField(blank=True, null=True)),
                ('total_user_ratings', models.IntegerField(default=0)),
                ('avg_processing_time_ms', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'ml_model_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_type', 'period_type'], name='ml_model_me_model_t_d4ebf6_idx'), models.Index(fields=['timestamp'], name='ml_model_me_timesta_acc1fa_idx')],
                'unique_together': {('model_type', 'period_type', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='MLPerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_type', models.CharField(choices=[('nutrition', 'Nutrition Recommendation'), ('workout', 'Workout Recommendation')], max_length=50)),
                ('approach_used', models.CharField(choices=[('ml_based', 'ML Based'), ('rule_based', 'Rule Based'), ('hybrid', 'Hybrid')], max_length=20)),
                ('confidence_score', models.FloatField(blank=True, help_text='ML model confidence score (0-1)', null=True)),
                ('processing_time_ms', models.IntegerField(help_text='Processing time in milliseconds')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, help_text='User rating (1-5 stars)', null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_performance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_performance_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MLPredictionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(help_text='Rating (1-5 stars)')),
                ('helpful', models.BooleanField(default=True, help_text='Was the recommendation helpful?')),
                ('accurate', models.BooleanField(default=True, help_text='Was the recommendation accurate?')),
                ('comments', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=True, help_text='Did user accept the recommendation?')),
                ('modified', models.BooleanField(default=False, help_text='Did user modify the recommendation?')),
                ('performance_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_features.mlperformancelog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_prediction_feedback',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='mlperformancelog',
            index=models.Index(fields=['timestamp'], name='ml_performa_timesta_448d60_idx'),
        ),
        migrations.AddIndex(
            model_name='mlperformancelog',
            index=models.Index(fields=['model_type'], name='ml_performa_model_t_76f1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='mlperformancelog',
            index=models.Index(fields=['approach_used'], name='ml_performa_approac_414357_idx'),
        ),
        migrations.AddIndex(
            model_name='mlpredictionfeedback',
            index=models.Index(fields=['user'], name='ml_predicti_user_id_b69b48_idx'),
        ),
        migrations.AddIndex(
            model_name='mlpredictionfeedback',
            index=models.Index(fields=['performance_log'], name='ml_predicti_perform_c1630f_idx'),
        ),
        migrations.AddIndex(
            model_name='mlpredictionfeedback',
            index=models.Index(fields=['timestamp'], name='ml_predicti_timesta_6a1ba1_idx'),
        ),
    ]
