# Generated by Django 6.0.2 on 2026-04-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0003_mlmodelmetrics_mlperformancelog_mlpredictionfeedback_and_more'),
    ]

    operations = [
    ]
